#!/usr/bin/env python3
"""html_export.py — publication PDF -> single self-contained HTML file.

Converts each PDF page to vector SVG (poppler's pdftocairo) and inlines all
pages into one HTML document: no external assets, crisp at any zoom, prints
back to landscape Letter one page per sheet. The PDF stays the canonical
publication; this exporter is re-run after any rebuild.

Usage:  python3 html_export.py <publication.pdf> [more.pdf ...]
Writes <publication>.html next to each input. Requires poppler-utils.
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

INK = "#212126"
GRAY = "#73737A"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body {{ margin: 0; background: #ECECEE; font-family: Helvetica, Arial, sans-serif; }}
  header {{ text-align: center; padding: 26px 12px 4px; }}
  header h1 {{ margin: 0; font-size: 20px; color: {ink}; }}
  header p {{ margin: 6px 0 0; font-size: 12px; color: {gray}; }}
  .page {{ background: white; box-shadow: 0 2px 10px rgba(33,33,38,0.18);
          margin: 22px auto; max-width: 1056px; }}
  .page svg {{ display: block; width: 100%; height: auto; }}
  .pageno {{ text-align: center; font-size: 11px; color: {gray}; margin: -12px 0 22px; }}
  footer {{ text-align: center; font-size: 11px; color: {gray}; padding: 8px 0 30px; }}
  @media print {{
    body {{ background: white; }}
    header, footer, .pageno {{ display: none; }}
    .page {{ box-shadow: none; margin: 0; max-width: none; page-break-after: always; }}
    @page {{ size: letter landscape; margin: 0; }}
  }}
</style>
</head>
<body>
<header><h1>{title}</h1><p>{pages} pages · At-Etudes · single-file HTML edition (vector; prints to landscape Letter)</p></header>
{body}
<footer>Generated by html_export.py from {pdf_name} — the PDF remains the canonical edition.</footer>
</body>
</html>
"""

def page_count(pdf):
    out = subprocess.run(["pdfinfo", str(pdf)], check=True, capture_output=True, text=True).stdout
    return int(re.search(r"^Pages:\s+(\d+)$", out, re.M).group(1))

def page_svg(pdf, n, tmpdir):
    out = Path(tmpdir) / f"p{n}.svg"
    subprocess.run(["pdftocairo", "-svg", "-f", str(n), "-l", str(n),
                    str(pdf), str(out)], check=True)
    svg = out.read_text()
    svg = svg[svg.index("<svg"):]                      # strip XML prolog
    # unique ids per page so inlined defs (glyphs, clips) never collide
    svg = re.sub(r'id="([^"]+)"', rf'id="pg{n}-\1"', svg)
    svg = re.sub(r'href="#([^"]+)"', rf'href="#pg{n}-\1"', svg)
    svg = re.sub(r'url\(#([^)]+)\)', rf'url(#pg{n}-\1)', svg)
    return svg

def export(pdf):
    pdf = Path(pdf)
    n = page_count(pdf)
    title = pdf.stem.replace("_", " ")
    parts = []
    with tempfile.TemporaryDirectory() as td:
        for p in range(1, n + 1):
            parts.append(f'<div class="page">{page_svg(pdf, p, td)}</div>'
                         f'<div class="pageno">{p} / {n}</div>')
    html = TEMPLATE.format(title=title, pages=n, body="\n".join(parts),
                           ink=INK, gray=GRAY, pdf_name=pdf.name)
    out = pdf.with_suffix(".html")
    out.write_text(html)
    print(f"{out.name}: {n} pages, {out.stat().st_size/1e6:.2f} MB")

if __name__ == "__main__":
    for arg in sys.argv[1:]:
        export(arg)
